// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// สร้าง connection URL รูปแบบ SQL Server สำหรับ Prisma CLI (db push / migrate)
// จาก env MSSQL_* ชุดเดียวกับที่ runtime ใช้ (lib/mssql-config.ts)
const {
  MSSQL_SERVER = "localhost",
  MSSQL_PORT = "1433",
  MSSQL_DATABASE = "requestonline",
  MSSQL_USER = "requestapp",
  MSSQL_PASSWORD = "",
} = process.env;

const url = `sqlserver://${MSSQL_SERVER}:${MSSQL_PORT};database=${MSSQL_DATABASE};user=${MSSQL_USER};password=${MSSQL_PASSWORD};encrypt=true;trustServerCertificate=true`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url,
  },
});
