// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// สร้าง connection URL รูปแบบ SQL Server สำหรับ Prisma CLI (db push / migrate)
// จาก env MSSQL_* ชุดเดียวกับที่ runtime ใช้ (lib/mssql-config.ts)
const {
  MSSQL_SERVER = "localhost",
  MSSQL_PORT = "1433",
  MSSQL_DATABASE = "requestonline",
  MSSQL_USER = "requestapp",
  MSSQL_PASSWORD = "",
  MSSQL_ENCRYPT = "true",
} = process.env;

// Encode credentials so passwords containing `@`, `;`, `:` or other URL
// delimiters are passed to Prisma CLI exactly as configured.
// SQL Server uses a JDBC-style semicolon connection string. Values containing
// delimiters must be wrapped in curly braces; URL-encoding is not equivalent.
function escapeSqlServerValue(value: string): string {
  return /[:\\=;/[\]{} ]/.test(value) ? `{${value}}` : value;
}

const url = `sqlserver://${MSSQL_SERVER}:${MSSQL_PORT};database=${escapeSqlServerValue(MSSQL_DATABASE)};user=${escapeSqlServerValue(MSSQL_USER)};password=${escapeSqlServerValue(MSSQL_PASSWORD)};encrypt=${MSSQL_ENCRYPT};trustServerCertificate=true`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url,
  },
});
